training_images_folders: [
  /data/pg-organoid_data/1CA5KMCR7K7MT53OS7FG/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/5ZBQ5VZO6IA5VHDX3X0U/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/L9YXESHQ6UDYDYTG3UP2/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/A5VHDX3X0UWN2VMLYD0Y/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/6QL9YXESHQ6UDYDYTG3U/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
]
training_segmentation_folders: [
  /data/pg-organoid_data/1CA5KMCR7K7MT53OS7FG/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/5ZBQ5VZO6IA5VHDX3X0U/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/L9YXESHQ6UDYDYTG3UP2/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/A5VHDX3X0UWN2VMLYD0Y/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
  /data/pg-organoid_data/6QL9YXESHQ6UDYDYTG3U/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
]
testing_images_folder: [
  /data/pg-organoid_data/P2R2WP36RVDLHB15I48C/Starvation_1_24H_For_ASMAA_Stitched/Stacks_crops_complete_window100_w320_h320, 
]
testing_segmentation_folder: [
  /data/pg-organoid_data/P2R2WP36RVDLHB15I48C/Starvation_1_24H_For_ASMAA_Stitched/Masks_crops_complete_window100_w320_h320, 
]

k: 5